### PR TITLE
Make sure that LCIO target is also available downstream

### PR DESCRIPTION
**Pull request by tmadlener**
BEGINRELEASENOTES
- Make sure the `LCIO::lcio` target is also defined in packages consuming Marlin (necessary after #56)

ENDRELEASENOTES

Otherwise some packages, e.g. `KiTrack` will not build / link for me.

### CODE REVIEW

**Comment by jmcarcell** [comment]
We can also not use `Marlin_LIBRARIES` which I would prefer even if it's more work since what's happening now is that some packages are linking a lot of stuff that they don't need, like `KiTrack` which doesn't need LCIO.

**Comment by tmadlener** [comment]
I agree whit cleaning up the downstream consumers. However, I also think that we still need to properly propagate the fact, that Marlin depends on LCIO. So we need both IMHO.

**Comment by jmcarcell** [comment]
With the four PRs that appear at the bottom of https://github.com/iLCSoft/Marlin/pull/56 I can build the stack and some missing dependencies are uncovered.

**Comment by jmcarcell** [comment]
> I agree whit cleaning up the downstream consumers. However, I also think that we still need to properly propagate the fact, that Marlin depends on LCIO. So we need both IMHO.

Then I think the target `LCIO::lcio` shouldn't be created, otherwise cases like `KiTrack` can't be discovered. And since this is a change being made now I don't think we should worry about older versions of `LCIO` that would need the `LCIO::lcio` target.

**Comment by tmadlener** [comment]
If we don't bootstrap the targets in the `MarlinConfig.cmake` we have to bump the minimum required version of LCIO that is necessary to build Marlin. Otherwise, this will not be fully transparent.

**Comment by tmadlener** [comment]
Should we merge this still today (or revert #56) to avoid breaking the nightlies?

**Comment by jmcarcell** [comment]
Let's merge this today

**Pull request merged**
