### PR TITLE
DOC: new doxygen does not like html files

### PR DESCRIPTION
**Pull request by andresailer**
newer versions of doxygen (1.8.8) are not treating unknown extensions, thus we rename overview.html to overview.txt
See https://www.stack.nl/~dimitri/doxygen/manual/faq.html "My file [...] is not parsed anymore"

BEGINRELEASENOTES
- Make Doxygen documentation compatible with doxygen 1.8.8+

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
The Ninja generator doesn't like the doc creation procedure

**Comment by rete** [comment]
Can you try with the standard Makefile generator and `make install` ? It should make the trick.

**Comment by rete** [comment]
Nice ! It seems that the overview.txt is [correctly processed](https://travis-ci.org/iLCSoft/Marlin/jobs/379769657#L909) by doxygen.

**Comment by andresailer** [comment]
https://sailer.web.cern.ch/sailer/Marlin/html/index.html

**Comment by andresailer** [comment]
Is everyone happy with this now? There are a few more packages which include html files into doxygen that need to get the same treatment.

**Comment by rete** [comment]
Everybody is happy !

**Pull request merged**
